

DROP TABLE IF EXISTS import_tasks;
DROP TABLE IF EXISTS recommendations;
DROP TABLE IF EXISTS vm_metrics;
DROP TABLE IF EXISTS snapshots;
DROP TABLE IF EXISTS vms;
DROP TABLE IF EXISTS compute_nodes;
DROP TABLE IF EXISTS images;
DROP TABLE IF EXISTS flavors;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS users;